### ISSUE TITLE
Error in Line 514 when running the code

### ISSUE THREAD

**Issue by bailingbird** [yalickj/load-forecasting-resnet#6]
When running the code, there is an error as follows,
Traceback (most recent call last):
  File "E:\LoadForecast\North American\ResNetPlus_North_American.py", line 514, in <module>
    history_1 = model.fit(X_train_fit, Y_train_fit, \
  File "C:\Users\huhai\AppData\Roaming\Python\Python39\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\huhai\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

**Comment by yalickj** [comment]
Is this the complete error message?
